-- TODO: Vytvorte tabulku expenses odpovidajici data class Expense
-- Hint: CREATE TABLE IF NOT EXISTS expenses (
--     id          INTEGER PRIMARY KEY AUTOINCREMENT,
--     description TEXT    NOT NULL,
--     amount      INTEGER NOT NULL,
--     date        TEXT    NOT NULL
-- );
